[package]
name = "convert"
version = "0.1.0"
edition = "2021"

[dependencies]
pdf_render = { path = "../../render" }
pdf = { workspace = true }
structopt = "*"
pathfinder_export = { workspace = true }
pathfinder_geometry = { workspace = true }
